"""
EKGQuest Realism Lab
====================

A Python toolkit for evaluating and improving synthetic ECG realism.

This lab provides:
- ECG JSON I/O utilities
- Realism metrics (distribution checks, physics consistency, morphology)
- Evaluation pipeline with configurable thresholds
- Report generation for CI/CD integration

Usage:
    python -m realism_lab.eval_realism --config configs/eval_matrix.json

The lab tests ECGs generated by the JS synthesizer, ensuring the
actual production code is what gets validated.
"""

__version__ = "1.0.0"

from .io_ecgjson import load_ecg_json, save_ecg_json, ECGData
from .metrics import (
    compute_physics_metrics,
    compute_distribution_metrics,
    compute_morphology_metrics,
    compute_hrv_metrics,
)
from .eval_realism import run_evaluation, EvaluationResult
from .report import generate_report

__all__ = [
    "load_ecg_json",
    "save_ecg_json",
    "ECGData",
    "compute_physics_metrics",
    "compute_distribution_metrics",
    "compute_morphology_metrics",
    "compute_hrv_metrics",
    "run_evaluation",
    "EvaluationResult",
    "generate_report",
]
