"""
EKGQuest Realism Lab
====================

A Python toolkit for evaluating and improving synthetic ECG realism.

This lab provides:
- ECG JSON I/O utilities
- Realism metrics (distribution checks, physics consistency, morphology)
- Evaluation pipeline with configurable thresholds
- Report generation for CI/CD integration

Usage:
    python -m realism_lab.eval_realism --config configs/eval_matrix.json

The lab tests ECGs generated by the JS synthesizer, ensuring the
actual production code is what gets validated.
"""

__version__ = "1.0.0"

from .io_ecgjson import load_ecg_json, save_ecg_json, ECGData
from .metrics import (
    compute_physics_metrics,
    compute_distribution_metrics,
    compute_morphology_metrics,
    compute_hrv_metrics,
    compute_spectral_metrics,
    SpectralMetrics,
)
from .eval_realism import run_evaluation, EvaluationResult
from .report import generate_report
from .pediatric_reference import (
    RIJNBEEK_REFERENCE,
    validate_ecg_against_rijnbeek,
    RijnbeekValidationResult,
    get_reference_value,
    compute_z_score_rijnbeek,
)
from .ptbxl_reference import (
    PTBXL_REFERENCE,
    compare_to_ptbxl,
    compute_ptbxl_realism_score,
    get_ptbxl_class,
)

__all__ = [
    "load_ecg_json",
    "save_ecg_json",
    "ECGData",
    "compute_physics_metrics",
    "compute_distribution_metrics",
    "compute_morphology_metrics",
    "compute_hrv_metrics",
    "compute_spectral_metrics",
    "SpectralMetrics",
    "run_evaluation",
    "EvaluationResult",
    "generate_report",
    # Pediatric reference (Rijnbeek 2001)
    "RIJNBEEK_REFERENCE",
    "validate_ecg_against_rijnbeek",
    "RijnbeekValidationResult",
    "get_reference_value",
    "compute_z_score_rijnbeek",
    # Adult reference (PTB-XL)
    "PTBXL_REFERENCE",
    "compare_to_ptbxl",
    "compute_ptbxl_realism_score",
    "get_ptbxl_class",
]
